# YOUR UFUTURE CREDENTIALS

[login]
username = 1234567890
password = "XXXXAAAAYYYY"

[ntfyServer]
url = "https://ntfy.sh/your_ntfy_topic"


# PERSISTENT TIMETABLE

[timetable.monday]
ICM451 = ['12:00PM', 'MK2']
IMC501 = ['2:30PM', 'MK8']
ICM454 = ['12:00PM', 'MK4']

[timetable.tuesday]
HBU137 = ['5:00PM', 'BK9']

[timetable.wednesday]
TAC451 = ['10:00AM', 'BK60/BK23']
EWC661 = ['2:00PM', 'BK19']

[timetable.thursday]

[timetable.friday]
ICM572 = ['10:00AM', 'MK3']
ENT530 = ['3:00PM', 'Bilik Seminar']


# OTHER INFORMATION REQUIRED
[academicInfo]
tarikh_tamat_semester_semasa = 2024-07-24 # YEAR-MO-DD (MUST FOLLOW THIS DATE FORMATTING)